---
:constants:
  :text: [240, 255, 240]

  :dark_background: [0, 30, 0]
  :light_background: [50, 120, 50]
  :hover_background: [120, 200, 120]

  :dark_border: [0, 30, 0]
  :light_border: [25, 60, 25]

  :handle: [80, 180, 80]

:elements:
  :Element:
    :font_name: ProggyCleanSZ.ttf
    :font_height: 16
    :color: ?text
    :background_color: ?none
    :border_color: ?light_background

  :Button:
    :disabled:
      :background_color: ?dark_background
      :border_color: ?dark_border
    :hover:
      :background_color: ?hover_background

  :Packer:
    :spacing_h: 8
    :spacing_v: 8
    :padding_left: 16
    :padding_right: 16
    :padding_top: 12
    :padding_bottom: 18

  :Button:
    :border_thickness: 2
    :padding_left: 12
    :padding_right: 12
    :padding_top: 4
    :padding_bottom: 4
    :background_color: ?light_background

  :ComboBox:
    :border_thickness: 0

  :MenuPane::Item:
    :padding_top: 0.4
    :padding_bottom: 0.4

  :ToolTip:
    :font_height: 16
    :padding_top: 4
    :padding_bottom: 4
    :background_color: ?dark_background

  :TextArea:
    :color: ?text
    :background_color: ?dark_background
    :font_height: 14
    
  :ScrollBar: # < Composite
    :rail_width: 14
    :rail_color: ?light_background
    :handle_color: ?handle

    
  :ScrollWindow: # < Composite
    :scroll_bar_thickness: 12
    :border_color: ?light_border
    :background_color: ?dark_background

